name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'parents-madrasa-portal/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          cd parents-madrasa-portal
          npm ci

      - name: Create environment file for build
        run: |
          cd parents-madrasa-portal
          echo "NODE_ENV=production" > .env.local
          echo "VITE_APP_ENV=production" >> .env.local
          echo "VITE_APP_VERSION=1.0.0" >> .env.local
          echo "VITE_FIREBASE_API_KEY=dummy" >> .env.local
          echo "VITE_FIREBASE_AUTH_DOMAIN=dummy.firebaseapp.com" >> .env.local
          echo "VITE_FIREBASE_PROJECT_ID=dummy" >> .env.local
          echo "VITE_FIREBASE_STORAGE_BUCKET=dummy.appspot.com" >> .env.local
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=123456789" >> .env.local
          echo "VITE_FIREBASE_APP_ID=1:123456789:web:abcdef" >> .env.local
          echo "VITE_ZOOM_ENABLED=false" >> .env.local
          echo "VITE_ANALYTICS_ENABLED=false" >> .env.local

      - name: Build application
        run: |
          cd parents-madrasa-portal
          npm run build
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: parents-madrasa-portal/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
